categories: [Proteomics]
description: OpenContact mapping for peptide mimetic discovery.
long_description: 
  OpenContact is an open source mapping algorithm for peptide mimetic discovery. 
  Peptide mimetics are short segments of functional proteins that can 
  interfere/inihibit protein-protein interactions (antagonist drugs) or 
  promote/enhance protein-protein interactions (agonist drugs).

  http://www.engineering.vcu.edu/proteinengineering/
  
name: opencontact
owner: jjohnson
