owner: jjohnson
name: spectrast2spectrast_irt
categories:
- Proteomics
description: Filter from spectraST files to swath input files
long_description: |
  Filter from spectraST files to swath input files.

  https://github.com/msproteomicstools/msproteomicstools
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/spectrast2spectrast_irt
type: unrestricted
