categories:
- Sequence Analysis
description: MiXCR processes immunome sequences to quantitated clonotypes
long_description: |
  MiXCR processes big immunome data from raw sequences to quantitated clonotypes

  MiXCR efficiently handles paired-end and single-end reads, considers sequence 
  quality, corrects PCR errors and identifies germline hypermutations. 
  

  https://milaboratory.com/software/mixcr/

name: mixcr
owner: jjohnson
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/mixcr
type: unrestricted
