categories:
- Text Manipulation
description: Loads tabular files into a SQLite DB to perform a SQL query producing a tabular output 
long_description: |
  Provides tools for manipulation of tablular files.  

  A variety of line filters may be applied to each line of a tabular file as it is read.  
  These filters can be used to select lines, select and reorder columns, 
  and normalize tabular files for use in a relational database.
  
  Regex regular expression functions re.match, re.search, and re.sub as defined in 
  SQLite databse connections, so that re.match, re.search, and re.sub can be used in SQL queries.

  The Query Tabular Loads tabular files into a new or existing SQLite DB to perform a SQL query 
  producing a tabular output.   It includes the line filtering options.
  The SQLite DB may optionally be saved as an additional output.

  The SQLite to Tabular tool performs a query on an existing SQLite DB.

  The Filter Tabular tool only uses the filtering options to produce a filtered tabaular output.

  http://www.sqlite.org/index.html
  https://docs.python.org/release/2.7/library/re.html

name: query_tabular
owner: jjohnson
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/query_tabular
type: unrestricted
